script: bundle exec rake
bundler_args: --without bin docs
branches:
  only:
  - master
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
- jruby
env:
  - COVERAGE=1 PURE_RUBY=1
  - COVERAGE=1 NOKOGIRI=1
  - COVERAGE=1 OX=1 OJ=1
gemfile:
  - Gemfile
matrix:
  exclude:
    # oj and ox gems do not build in jruby
    - rvm: jruby
      env: COVERAGE=1 OX=1 OJ=1
      gemfile: Gemfile
