name: "Close stale issues"

# Controls when the action will run.
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v3
      with:
        # Setting messages to an empty string will cause the automation to skip
        # that category
        ancient-issue-message: Greetings!! We noticed that this issue is very old and has not been updated in a very long time. We will close this issue for now. Please feel free to reach out and open a new issue if you think this is still a relevant issue or if it is an error.
        stale-issue-message: This issue has not recieved a response in 1 week. If you still think it is a persisting issue, please leave a comment to avoid the auto-close.

        # These labels are required
        stale-issue-label: closing-soon
        exempt-issue-label: no-autoclose
        stale-pr-label: closing-soon
        exempt-pr-label: pr/needs-review
        response-requested-label: response-requested

        # Don't set closed-for-staleness label to skip closing very old issues
        # regardless of label
        closed-for-staleness-label: closed-for-staleness

        # Issue timing
        days-before-stale: 7
        days-before-close: 4
        days-before-ancient: 1095

        # If you don't want to mark a issue as being ancient based on a
        # threshold of "upvotes", you can set this here. An "upvote" is
        # the total number of +1, heart, hooray, and rocket reactions
        # on an issue.
        minimum-upvotes-to-exempt: 10

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        # dry-run: true
